-- Add structured refund/audit columns to security_deposits
ALTER TABLE `security_deposits`
  ADD COLUMN `DEDUCTION_AMOUNT` DECIMAL(12, 2) NULL DEFAULT NULL AFTER `AMOUNT`,
  ADD COLUMN `CASH_REFUND_AMOUNT` DECIMAL(12, 2) NULL DEFAULT NULL AFTER `DEDUCTION_AMOUNT`,
  ADD COLUMN `APPLIED_TO_BALANCE` DECIMAL(12, 2) NULL DEFAULT NULL AFTER `CASH_REFUND_AMOUNT`,
  ADD COLUMN `REFUNDED_BY` INT NULL DEFAULT NULL AFTER `REFUNDED_AT`;
