-- Check-in notifier log (tracks notification windows per booking)
CREATE TABLE IF NOT EXISTS `check_in_notifier_log` (
  `IDNo` INT NOT NULL AUTO_INCREMENT,
  `BOOKING_ID` INT NOT NULL,
  `NOTIFY_WINDOW` VARCHAR(10) NOT NULL COMMENT '1day, 3day, 7day',
  `REFERENCE_CHECKIN_DATE` DATE NOT NULL,
  `ENCODED_BY` INT NULL DEFAULT NULL,
  `ENCODED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`IDNo`),
  UNIQUE KEY `uq_booking_window_checkin` (`BOOKING_ID`, `NOTIFY_WINDOW`, `REFERENCE_CHECKIN_DATE`),
  KEY `idx_notifier_checkin_date` (`REFERENCE_CHECKIN_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
